### ISSUE TITLE
Persistent Minecraft World and Allowing Cheats

### ISSUE THREAD

**Issue by QuantumArjun** [cocacola-lab/MineLand#13]
Thank you for the quick response to my last question! I'm trying to build an environment for the agents to do tasks in, but I'm finding that when I build my Minecraft world and move it into the sims folder, and I load from that world, it's reverting to using the base version of that world (i.e with none of my buildings in it). How would I get it to use the world that I've built? 

And a part 2 to this question - in my built world, I allow cheats, but when I load it through MineLand, I am no longer able to access those commands (when I log into the server my own client). I've tried editing the level.dat and the server.properties and neither of these seem to work.

Thank you so much in advance!

**Comment by lovekdl** [comment]
About the part1 to your question, please name your world folder `normal_world` and move it into the `mineland/sim/server` folder.

This is because Mineland, in order to maintain the consistency of each experiment, would replace the `normal_world` folder with the `world` folder, resulting in the initial world being used every time Mineland restarted.

If you solve the part1 question and still have the part2 question, please tell us.

Thank you!
