### ISSUE TITLE
Alex learning process

### ISSUE THREAD

**Issue by jbarrerobuch** [cocacola-lab/MineLand#24]
Hi there

I've left Alex living in an environment with the general goal of 'Playground' if I recall right But it just collects wood. Never crafted a crafting table nor a tool of any kind.
I thought it could be convenient to train it first on smaller specific tasks and allow it to gather skilled code info. So I started to with the most simple one. Collect one log.
However setting this goal is worst and not even collecting one single log but it says in the chat it did collect it. The inventory is empty and critic of course is to continue with the task.

Not sure if it could be related to be using Gemini instead of GPT.
I'm using the feee tier, did you have bad experience with this or didn't test it at all.
The answers seems correct, how did you supervise the LLM/VLM behavior?

Is this a matter of time and letting try and try?

Thanks! 😊

**Comment by YXHXianYu** [comment]
> Alex Never crafted a crafting table nor a tool of any kind.
>
> this goal is worst and not even collecting one single log

According to your description, These problems are all due to Gemini's insufficient ability to generate Mineflayer code (action module) and has no sufficient ability to accurately evaluate whether it have completed the plan.

I tested gpt-3.5, gpt-4, gpt-4o. Only the gpt4 has the ability to learn and improve itself. (it may also be trapped in some cases)

This part, you can refer to Voyager. It has the same problem. (Because the architectures of them are similar)

> The answers seems correct, how did you supervise the LLM/VLM behavior?

"supervise" means a lot. Fundenmentally, we evaluate LLM/VLM by using task outcomes (Success or Failure) and the number of  iterations the agent requires to complete the tasks.

> Is this a matter of time and letting try and try?

In fact, no. In your case, the primary issue is the LLM/VLM's insufficient capability, not the amount of time or retries.

I hope these answers help!

**Comment by YXHXianYu** [comment]
> The answers seems correct, how did you supervise the LLM/VLM behavior?

In fact, I am only responsible for the MineLand Simulator part, and I'm not very familiar with Alex. If you have any further questions, I can go to Alex's developer.

**Comment by jbarrerobuch** [comment]
ok, seems the LLM is the cause I'll get back to it. Do yo have any estimations on costs to run one instance of Alex?
TY

**Comment by FooLiqi** [comment]
In our experiments, we use gpt4o and the cost is 0.118 usd/iteragtion*agent. sorry for being late lol
