### ISSUE TITLE
stage_performance_2_agent_date

### ISSUE THREAD

**Issue by WPH22** [cocacola-lab/MineLand#34]
Hello,

I want to try Stage Performance Tasks, but the three bots in the game did not start performing as I expected, but were still thinking about collecting wood... And only one of the three bots moved, while the other two just stood there in a daze. Is there something wrong with my settings? Here is my startup code:
<img width="559" alt="image" src="https://github.com/user-attachments/assets/da0fba1e-5a3e-42c6-81c9-c42909268531">

**Comment by YXHXianYu** [comment]
Stage Performance Tasks are developed by @lovekdl and I don't familiar with this part of code. I just checked this part of code and I found there may be some mistake.

I will submit a pull request soon, and provide a simple example to show how to get enuough information of stage performance tasks.

And sorry for that I have no time to provide a complete example because I'm busy with other projects. If you implement a good stage performance tasks example, you can submit a pull quest. I will carefully review it and try my best to get it merged.

**Comment by YXHXianYu** [comment]
I have merged the pr. You can use `git pull origin main` to get latest code. The new example is `scripts/stage_performance_task.py`.

And I fixed the mistake in description files. I know you found that, too. 😄 😄 Be free to create a pull request if you want.

**Comment by YXHXianYu** [comment]
To be honest, I'm not sure.

But according to `alex_example.py`, it looks correct.

**Comment by WPH22** [comment]
thanks!
